// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using faegtodo.Db;

namespace faegtodo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200612204355_AddClient")]
    partial class AddClient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("faegtodo.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rua lalalal 1000",
                            Birthday = new DateTime(2020, 6, 12, 20, 43, 55, 642, DateTimeKind.Local).AddTicks(367),
                            Name = "Zezinho"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rua lulull 200",
                            Birthday = new DateTime(2020, 6, 12, 20, 43, 55, 643, DateTimeKind.Local).AddTicks(5590),
                            Name = "Huguinho"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
